### ISSUE TITLE
MQTT credentials

### ISSUE THREAD

**Issue by JLFN** [git-developer/tvheadend-mqtt#1]
Can you please add the possiblity to use MQTT credentials username,password,clientid.
Thx you in advance.

**Comment by git-developer** [comment]
Please check if the environment variable `MQTT_PUBLISH_OPTIONS` fulfils your needs. Its content is appended to the `mosquitto_pub` call.

Example:
```MQTT_PUBLISH_OPTIONS='-u username -P password -i client_id'```

**Comment by JLFN** [comment]
Hey I tried like this but i didnt accept the login

````.yaml
#https://github.com/git-developer/tvheadend-mqtt
version: "2"
services:
  tvheadend-mqtt:
    image: "ckware/tvheadend-mqtt:latest"
    container_name: "tvheadend-mqtt"
    restart: unless-stopped
    environment:
      - TVHEADEND_USER=myuser
      - TVHEADEND_PASSWORD=password
      - TVHEADEND_HOST=192.168.1.12
      - MQTT_BROKER_HOSTNAME=192.168.1.2
      # - TVHEADEND_HTTP_PORT: 9981
      # - TVHEADEND_HTTP_URL: 192.168.1.2
      - TVHEADEND_HTTP_TIMEOUT=15
      - MQTT_TOPIC_PREFIX=tvheadend
      - MQTT_PUBLISH_OPTIONS='-u myuser -P "!Veryhardpassword!" -i tvheadend-mqtt'
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /home/${USER}/tvheadend-mqtt/config:/config
 #    support for publishing triggered by Tvheadend (optional)
      # - /home/${USER}/tvheadend-mqtt:/app/markers
   # support for user-defined plugins (optional)
      # - /home/${USER}/tvheadend-mqtt/plugins:/app/plugins
```

**Comment by git-developer** [comment]
I just tried a small example with authentication, and it worked.

Maybe a quoting issue? Could you try:
* `MQTT_PUBLISH_OPTIONS="-u myuser -P !Veryhardpassword! -i tvheadend-mqtt"`
* `MQTT_PUBLISH_OPTIONS="-u myuser -P '!Veryhardpassword!' -i tvheadend-mqtt"`

Another option (just to find out the issue) is to check if a simple password works.

Do you have an error message?

**Comment by git-developer** [comment]
Another idea: try to declare the environment variables as dictionary, not as list. The following example works for me:
```yaml
    environment:
      TVHEADEND_USER: "tvh-user"
      TVHEADEND_PASSWORD: "tvh-password"
      TVHEADEND_HOST: "tvheadend-host"
      TVHEADEND_HTTP_PORT: "9981"
      MQTT_BROKER_HOSTNAME: "broker-host"
      MQTT_PUBLISH_OPTIONS: "-u broker-user -P broker-password"
```

**Comment by git-developer** [comment]
From [docker-compose - how to escape environment variables](https://stackoverflow.com/a/41988810/9984216):
> Environment variables (including their name), **have to be fully wrapped inside single or double quotes**: `""` or `''`

Examples:
```
environment:
  - 'NODE_CONFIG={"database": {"data": {"host": "mongo"}, "session": {"host": "redis" }}}'
```

```
environment:
  - 'PORT=3000'
  - "NODE_CONFIG={\"database\": {\"data\": {\"host\": \"mongo\"}, \"session\": {\"host\": \"redis\" }}}"
```

**Comment by JLFN** [comment]
I got the same error when i tried I dont have possible to test with easy password, i dont userstand who i should try with the quotes like about  :
```.yaml
version: "2"
services:
  tvheadend-mqtt:
    image: "ckware/tvheadend-mqtt:latest"
    container_name: "tvheadend-mqtt"
    restart: unless-stopped
    environment:
      TVHEADEND_USER: myuser
      TVHEADEND_PASSWORD: myhardpassword
      TVHEADEND_HOST: 192.168.1.2
      MQTT_BROKER_HOSTNAME: 192.168.1.2
      # - TVHEADEND_HTTP_PORT: 9981
      # - TVHEADEND_HTTP_URL: 192.168.1.2
      TVHEADEND_HTTP_TIMEOUT: 15
      MQTT_TOPIC_PREFIX: tvheadend
      MQTT_PUBLISH_OPTIONS: -u "myuser" -P  "veryhardpassword?" -i "tvheadend-mqtt"
      PUID: 1000
      PGID: 1000
      TZ: Europe/Stockholm
    volumes:
      - /home/${USER}/tvheadend-mqtt/config:/config
 #    support for publishing triggered by Tvheadend (optional)
      # - /home/${USER}/tvheadend-mqtt:/app/markers
   # support for user-defined plugins (optional)
      # - /home/${USER}/tvheadend-mqtt/plugins:/app/plugins

**Comment by git-developer** [comment]
Try:

> ```yaml
> ...
>     environment:
>       TVHEADEND_USER: "myuser"
>       TVHEADEND_PASSWORD: "myhardpassword"
>       TVHEADEND_HOST: "192.168.1.2"
>       MQTT_BROKER_HOSTNAME: "192.168.1.2"
>       TVHEADEND_HTTP_TIMEOUT: "15"
>       MQTT_TOPIC_PREFIX: "tvheadend"
>       MQTT_PUBLISH_OPTIONS: "-u myuser -P 'veryhardpassword?' -i tvheadend-mqtt"
> ...
> ```

By the way: `veryhardpassword?` must only be quoted when it contains spaces or quotes.

**Comment by JLFN** [comment]
I also tried with ```.yaml
MQTT_PUBLISH_OPTIONS: -u myuser -p !v3ryh4rdp4ssw0rd? -i tvheadend-mqtt
```

**Comment by git-developer** [comment]
Should be
```.yaml
    MQTT_PUBLISH_OPTIONS: "-u myuser -P !v3ryh4rdp4ssw0rd? -i tvheadend-mqtt"
```
(with quotes and uppercase P)

**Comment by git-developer** [comment]
If it still doesn't work: are you able to call `mosquitto_pub` from the command line of the host where `tvheadend-mqtt` is running?
```
$ mosquitto_pub -h 192.168.1.2 -t tvheadend/test -m test -u myuser -P !v3ryh4rdp4ssw0rd? -i tvheadend-mqtt
```

**Comment by JLFN** [comment]
I tried  works and i could see the topic publish : ``` mosquitto_pub -u username -P '!veruhardpassword?' -h 192.168.1.2 -i tvheadend-mqtt -t tvheadend/test -m test ```

**Comment by git-developer** [comment]
OK, next try the same from within the Docker container (add `sudo` if required):
```
$ docker exec tvheadend-mqtt mosquitto_pub -h 192.168.1.2 -t tvheadend/test -m test -u myuser -P !v3ryh4rdp4ssw0rd? -i tvheadend-mqtt
```

**Comment by JLFN** [comment]
I tried this inside the docker and also i got message pubish ```oi@leblue:~/docker/tvheadend-mqtt$ docker exec tvheadend-mqtt mosquitto_pub -u moi -P '!v3rymuchmustardinthotdog?' -h 192.168.1.2 -i tvheadend-mqtt -t tvheadend/test -m testing_inside_docker```

**Comment by git-developer** [comment]
OK, then please check if the environment variables are set correctly inside the container:
```
$ docker exec tvheadend-mqtt env
```

**Comment by git-developer** [comment]
```
$ docker exec tvheadend-mqtt env | grep MQTT_PUBLISH_OPTIONS
```
should return:
```
MQTT_PUBLISH_OPTIONS=-u moi -P !v3ryh4rdp4ssw0rd? -i tvheadend-mqtt
```

**Comment by JLFN** [comment]
```me@boomm:~/docker/tvheadend-mqtt$ docker exec tvheadend-mqtt env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=128a1551011f
TVHEADEND_USER=myusername
TVHEADEND_PASSWORD=Fastiscpasswod
TVHEADEND_HOST=192.168.1.2
MQTT_BROKER_HOSTNAME=192.168.1.2
TVHEADEND_HTTP_TIMEOUT=15
MQTT_TOPIC_PREFIX=tvheadend
MQTT_PUBLISH_OPTIONS=-u mysusername -P '!l0v3tom4k3c0d3?' -i tvheadend-mqtt
PUID=1000
PGID=1000
TZ=Europe/Stockholm
HOME=/root
me@boomm:~/docker/tvheadend-mqtt$````

**Comment by JLFN** [comment]
It looks  same ```MQTT_PUBLISH_OPTIONS=-u myuser -P '!hloveactuce?' -i tvheadend-mqtt````

**Comment by git-developer** [comment]
The single quotes around `-P '!l0v3tom4k3c0d3?'` should not be there. Are these quotes part of the password?

**Comment by JLFN** [comment]
quotas are not part of the password

**Comment by git-developer** [comment]
Congratulations!

Please test carefully if your problem is solved. If so, please close the issue.

**Comment by JLFN** [comment]
> Congratulations!
> 
> Please test carefully if your problem is solved. If so, please close the issue.

Its not solved i was tired and open wrong docker when i checked it the logs.

**Comment by git-developer** [comment]
OK. Next steps:
1. Remove the single quotes around the password in `docker-compose.yml`
1. Restart container: `$ docker-compose down && docker-compose up -d`
1. Run `$ docker exec tvheadend-mqtt env | grep MQTT_PUBLISH_OPTIONS` and check if the quotes have gone.

**Comment by git-developer** [comment]
@JLFN Could you give a short status report?

**Comment by JLFN** [comment]
I deleted the single quotas and remove the docker the error. Same problem
2020-06-16 16:14:15 subscribe


Connection error: Connection Refused: not authorised.

i did what you said with docker-compose down && docker-compose up -d
 and also this step.
```
superduperuser@hardshell:~$ cd /home/superduperuser/docker/tvheadend-mqtt
superduperuser@hardshell:~/docker/tvheadend-mqtt$ docker-compose up -d
Creating tvheadend-mqtt ... done
superduperuser@hardshell:~/docker/tvheadend-mqtt$ docker exec tvheadend-mqtt env | grep MQTT_PUBLISH_OPTIONS
MQTT_PUBLISH_OPTIONS=-u superduperuser -P !v3ryindeedhard0ne? -i tvheadend-mqtt
superduperuser@hardshell:~/docker/tvheadend-mqtt$
```

**Comment by git-developer** [comment]
OK. Could you next try if the following works:
```
$ docker exec tvheadend-mqtt sh -c 'mosquitto_pub -h $MQTT_BROKER_HOSTNAME -t ${MQTT_TOPIC_PREFIX:-tvheadend}/test -m test-message -u superduperuser -P !v3ryindeedhard0ne? -i tvheadend-mqtt'
```

**Comment by JLFN** [comment]
That works i see the published message
and also this works
$ docker exec tvheadend-mqtt sh -c 'mosquitto_pub -h $MQTT_BROKER_HOSTNAME -t ${MQTT_TOPIC_PREFIX:-tvheadend}/test -m test-message -u superduperuser -P "!v3ryindeedhard0ne?" -i tvheadend-mqtt'

**Comment by git-developer** [comment]
OK. And how about
```
$ docker exec tvheadend-mqtt sh -c 'mosquitto_pub -h $MQTT_BROKER_HOSTNAME -t ${MQTT_TOPIC_PREFIX:-tvheadend}/test -m test-message $MQTT_PUBLISH_OPTIONS'
```

**Comment by JLFN** [comment]
That works also,
i see the message

**Comment by git-developer** [comment]
Next one is
```
$ docker exec tvheadend-mqtt sh -c 'echo "$MQTT_PUBLISH_OPTIONS" | xargs mosquitto_pub -h "$MQTT_BROKER_HOSTNAME" -t "${MQTT_TOPIC_PREFIX:-tvheadend}/test" -m test-message'
```

**Comment by JLFN** [comment]
That one also work.

**Comment by JLFN** [comment]
> Next one is
> 
> ```
> $ docker exec tvheadend-mqtt sh -c 'echo "$MQTT_PUBLISH_OPTIONS" | xargs mosquitto_pub -h "$MQTT_BROKER_HOSTNAME" -t "${MQTT_TOPIC_PREFIX:-tvheadend}/test" -m test-message'
> ```

that one also work

**Comment by git-developer** [comment]
And finally 
```
$ docker exec tvheadend-mqtt sh -c '/app/bin/main publish subscriptions'
```

**Comment by JLFN** [comment]
i did this
me@box:~/docker/tvheadend-mqtt$ docker exec tvheadend-mqtt sh -c '/app/bin/main publish subscriptions
> testar202006170918

It looks like this on Mqtt explorer.
````
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<HTML><HEAD>
<TITLE>401 Unauthorized</TITLE>
</HEAD><BODY>
<H1>401 Unauthorized</H1>
<P STYLE="text-align: center; margin: 2em"><A HREF="/" STYLE="border: 1px solid; border-radius: 4px; padding: .6em">Default login</A></P><P STYLE="text-align: center; margin: 2em"><A HREF="/login" STYLE="border: 1px solid; border-radius: 4px; padding: .6em">New login</A></P></BODY></HTML>
```

**Comment by git-developer** [comment]
Your MQTT credentails are OK, but your Tvheadend credentials are not. Please check if the Tvheadend user is configured properly and if the credentials are correct.

**Comment by JLFN** [comment]
i did cp and paste the password and tried to log in with tvheadend with the same user and password with chrome.I tried two user both are admins. I have no Ip rescriction and its install on the same docker host and i tried with same network stack and also host no change. is there way to use curl command inside the docker to rest the password or to reach the tvheand? ping works .

**Comment by git-developer** [comment]
Yes. Try:
```
$ docker exec tvheadend-mqtt sh -c 'curl -u $TVHEADEND_USER:$TVHEADEND_PASSWORD http://$TVHEADEND_HOST:${TVHEADEND_HTTP_PORT:-9981}/api/status/subscriptions'
```

**Comment by JLFN** [comment]
curl its not working inside ssh shell but the strange thing if i ssh tunnel tru the same ssh and open with chrome http://192.168.1.112:9981/api/status/subscriptions then enter the password it works. but not inside curl on docker the container is using network: host

**Comment by JLFN** [comment]
I see no login atempt either with i check logs.

**Comment by JLFN** [comment]
This work for me  curl --anyauth --user username:password http://192.168.1.112:9981/api/status/subscriptions

**Comment by JLFN** [comment]
This work for me :) Can you please add --anyauth to your code ?
``` curl --anyauth --user username:password http://192.168.1.112:9981/api/status/subscriptions ```
source: 
https://ec.haxx.se/http/http-auth

**Comment by git-developer** [comment]
I just built a new image with that parameter, please pull and try.

**Comment by JLFN** [comment]
Same problem, i also even did a own docker build to make sure

**Comment by git-developer** [comment]
I don't understand: how can you get _401 Unauthorized_ as response on the one hand but see no login attempt on the other side?

Maybe running `curl` verbosely will reveal something.

**Comment by JLFN** [comment]
I found out why it didnt work. Under HTTP server Settings you can choose Authentication type the default value for Build: 4.3-1886~g51a4c5bec (2020-06-12T04:50:42+0200) is Digest if i switch to plain( less secure it works) with the right command for digest should be ````curl --digest --user myuser:password http://192.168.1.112:9981/api/status/subscriptions```` adding ```  curl_options="$curl_options --digest"` didnt work
![image](https://user-images.githubusercontent.com/22047436/84939010-f3a29180-b0dd-11ea-90c1-c3f41ff3e2ad.png)

**Comment by JLFN** [comment]
With this settings
![image](https://user-images.githubusercontent.com/22047436/84940016-842da180-b0df-11ea-8565-98ce24e4369a.png)

I did this instead docker bin/sh
```.sh

 #  curl --user username:password http://192.168.1.112:9981/api/status/subscriptions
{"entries":[{"id":309,"start":1592420767,"errors":0,"state":"Running","title":"epggrab","service":"SAT>IP DVB-S Tuner #1 (192.168.1.166@UDP)/Hotbird/11880V/Raw PID Subscription","pids":[0,1,16,17,18],"in":27646,"out":1702,"total_in":16482714,"tota/ 
#  curl --digest --user username:passsword http://192.168.1.112:9981/api/status/subscriptions
{"entries":[{"id":309,"start":1592420767,"errors":0,"state":"Running","title":"epggrab","service":"SAT>IP DVB-S Tuner #1 (192.168.1.166@UDP)/Hotbird/11880V/Raw PID Subscription","pids":[0,1,16,17,18],"in":44057,"out":1757,"total_in":16745830,"total_out":647766}],"totalCount":1}/ # 
```

**Comment by git-developer** [comment]
Does that mean it finally works for you with Authentication type _Both plain and digest_?

**Comment by JLFN** [comment]
Summary the curl command that works inside docker but doenst work with tvheadend.
```
 #  curl --user username:password http://192.168.1.112:9981/api/status/subscriptions
{"entries":[{"id":309,"start":1592420767,"errors":0,"state":"Running","title":"epggrab","service":"SAT>IP DVB-S Tuner #1 (192.168.1.166@UDP)/Hotbird/11880V/Raw PID Subscription","pids":[0,1,16,17,18],"in":27646,"out":1702,"total_in":16482714,"tota/ 
#  curl --digest --user username:passsword http://192.168.1.112:9981/api/status/subscriptions
{"entries":[{"id":309,"start":1592420767,"errors":0,"state":"Running","title":"epggrab","service":"SAT>IP DVB-S Tuner #1 (192.168.1.166@UDP)/Hotbird/11880V/Raw PID Subscription","pids":[0,1,16,17,18],"in":44057,"out":1757,"total_in":16745830,"total_out":647766}],"totalCount":1}/ # 
```

**Comment by git-developer** [comment]
I do not understand your last message. What exactly do you mean by _command_ (you show 2 different commands with different passwords), by _inside docker_ (inside `tvheadend-mqtt` container?) and by _with tvheadend_?

I published another Docker image today that supports a new environment variable `TVHEADEND_CURL_OPTIONS` for additional curl arguments. You may set that to `--anyauth --digest`. See the [Authentication](https://github.com/git-developer/tvheadend-mqtt/tree/develop#example-mqtt-authentication-and-tvheadend-digest-authentication) section of the documentation for an example.

**Comment by JLFN** [comment]
WIth tvheadend default settings that is digest:
i did inside docke tvheadend-mqtt containerr :
````
curl --digest --user username:passsword http://192.168.1.112:9981/api/status/subscriptions

#and i got the ouput

{"entries":[{"id":309,"start":1592420767,"errors":0,"state":"Running","title":"epggrab","service":"SAT>IP DVB-S Tuner #1 (192.168.1.166@UDP)/Hotbird/11880V/Raw PID Subscription","pids":[0,1,16,17,18],"in":44057,"out":1757,"total_in":16745830,"total_out":647766}],"totalCount":1}/ # 
````

**Comment by JLFN** [comment]
i logged in inside the docker tvheadend-mqtt container and did the 
command ````curl --digest --user username:passsword http://192.168.1.112:9981/api/status/subscriptions````
that out was was showing.
But still nothing working with tvheadend-mqtt

**Comment by git-developer** [comment]
OK. When it works within the Docker container manually, we should get it working for `tvheadend-mqtt`, too.

1. Check that your `docker-compose.yml` contains
    ```yaml
        image: "ckware/tvheadend-mqtt:latest"
        environment:
            TVHEADEND_CURL_OPTIONS: "--anyauth --digest"
    ```
1. Update the image and restart the container:
    ```
    $ docker-compose down
    $ docker-compose pull
    $ docker-compose up -d
    ```
1. Check that `TVHEADEND_CURL_OPTIONS` is set:
    ```
    $ docker exec tvheadend-mqtt env | grep TVHEADEND_CURL_OPTIONS
    TVHEADEND_CURL_OPTIONS=--anyauth --digest
    ```
1. Run `curl`. Run the command as is, do not manually replace the environment variables:
    ```
    $ docker exec tvheadend-mqtt sh -c 'curl $TVHEADEND_CURL_OPTIONS -u $TVHEADEND_USER:$TVHEADEND_PASSWORD http://$TVHEADEND_HOST:${TVHEADEND_HTTP_PORT:-9981}/api/status/subscriptions'
    ```
1. Run a `tvheadend-mqtt` command:
    ```
    docker exec tvheadend-mqtt sh -c '/app/bin/main publish subscriptions'
    ```

**Comment by JLFN** [comment]
You cant use --anyauth or digest together --anyauth =auto select

**Comment by git-developer** [comment]
OK, then use whatever is appropriate for your configuration.

**Comment by JLFN** [comment]
```
#1
me@mybox:~/docker_compose/tvheadend-mqtt$ docker-compose down
Stopping tvheadend-mqtt ... done
Removing tvheadend-mqtt ... done
#2
me@mybox:~/docker_compose/tvheadend-mqtt$ docker-compose pull
Pulling tvheadend-mqtt ... done
#3
me@mybox:~/docker_compose/tvheadend-mqtt$ docker-compose up -d
Creating tvheadend-mqtt ... done
#4
me@mybox:~/docker_compose/tvheadend-mqtt$ docker exec tvheadend-mqtt env | grep TVHEADEND_CURL_OPTIONS
TVHEADEND_CURL_OPTIONS=--digest
#5 Result no mqtt publish
me@mybox:~/docker_compose/tvheadend-mqtt$ docker exec tvheadend-mqtt sh -c 'curl $TVHEADEND_CURL_OPTIONS -u $TVHEADEND_USER:$TVHEADEND_PASSWORD http://$TVHEADEND_HOST:${TVHEADEND_HTTP_PORT:-9981}/api/status/subscriptions'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   432  100   432    0     0   421k      0 --:--:-- --:--:-- --:--:--  421k
{"entries":[{"id":710,"start":1592461442,"errors":0,"state":"Bad","title":"epggrab","service":"SAT>IP DVB-S Tuner #1 (192.168.1.166@UDP)/Astra 19.2E/10920.75H/Raw PI100   262  100   262    0     0   255k      0 --:--:-- --:--:-- --:--:--  255k0}],"totalCount":1}
#6 Result mqtt was publish and showed on MQTT explorer
me@mybox:~/docker_compose/tvheadend-mqtt$ docker exec tvheadend-mqtt sh -c '/app/bin/main publish subscriptions'
No plugins found.
2020-06-18 08:29:20 publish subscriptions
me@mybox:~/docker_compose/tvheadend-mqtt$

#7 Test curl command 
me@mybox:~/docker_compose/tvheadend-mqtt$ docker exec tvheadend-mqtt sh -c 'curl --digest --user user:password http://192.168.1.112:9981/api/status/subscriptions'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   432  100   432    0     0   421k      0 --:--:-- --:--:-- --:--:--  421k
100   262  100   262    0     0   255k      0 --:--:-- --:--:-- --:--:--  255k
{"entries":[{"id":710,"start":1592461442,"errors":0,"state":"Bad","title":"epggrab","service":"SAT>IP DVB-S Tuner #1 (192.168.1.166@UDP)/Astra 19.2E/10920.75H/Raw PID Subscription","pids":[0,1,16,17,18],"in":0,"out":0,"total_in":0,"total_out":0}],"totalCount":1}

```

**Comment by git-developer** [comment]
You say that command no. 6 was published. That means it's working now.

**Comment by JLFN** [comment]
#5 Result Not mqtt publish
me@mybox:~/docker_compose/tvheadend-mqtt$ docker exec tvheadend-mqtt sh -c 'curl $TVHEADEND_CURL_OPTIONS -u $TVHEADEND_USER:$TVHEADEND_PASSWORD http://$TVHEADEND_HOST:${TVHEADEND_HTTP_PORT:-9981}/api/status/subscriptions'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   432  100   432    0     0   421k      0 --:--:-- --:--:-- --:--:--  421k
{"entries":[{"id":710,"start":1592461442,"errors":0,"state":"Bad","title":"epggrab","service":"SAT>IP DVB-S Tuner #1 (192.168.1.166@UDP)/Astra 19.2E/10920.75H/Raw PI100   262  100   262    0     0   255k      0 --:--:-- --:--:-- --:--:--  255k0}],"totalCount":1}
#6 Result mqtt was publish and showed on MQTT explorer

**Comment by JLFN** [comment]
Why dont i see nothing when i start tvheadend-mqtt ?
i see only when i do command
 ``` 
docker exec tvheadend-mqtt sh -c '/app/bin/main publish subscriptions' 
```

**Comment by JLFN** [comment]
The strange thing i still get on the docker log ````
No plugins found.


2020-06-18 08:56:20 subscribe


Connection error: Connection Refused: not authorised.

````

**Comment by JLFN** [comment]
How can i make sure init is running inside docker?
```
#!/bin/sh
/app/bin/main subscribe &
exec inotifyd /app/bin/inotify_handler /app/markers/:ce
```

**Comment by JLFN** [comment]
```
me@mybox:~/docker_compose/tvheadend-mqtt$ docker exec -it tvheadend-mqtt /bin/sh
/ # ./app/bin/main subscribe
No plugins found.
2020-06-18 10:10:54 subscribe
Connection error: Connection Refused: not authorised.
/ #````
No mqtt was published

**Comment by git-developer** [comment]
> Why dont i see nothing when i start tvheadend-mqtt ?

tvheadend-mqtt is waiting for commands. See [How it works](https://github.com/git-developer/tvheadend-mqtt#how-it-works) for the basic workflow. You can also configure Tvheadend to push messages on events automatically. See [Publishing triggered by Tvheadend](https://github.com/git-developer/tvheadend-mqtt#publishing-triggered-by-tvheadend) for details.

> 2020-06-18 08:56:20 subscribe
>
> Connection error: Connection Refused: not authorised.

tvheadend-mqtt uses 
1. MQTT _subscribe_ to listen to requests and
1. MQTT _publish_ to send Tvheadend info

You added your credentials for the publish part. You will have to add your credentials to `MQTT_SUBSCRIBE_OPTIONS`, too :
```yaml
    MQTT_SUBSCRIBE_OPTIONS: "-u superduperuser -P !v3ryindeedhard0ne? -i tvheadend-mqtt-subscriber"
```

**Comment by git-developer** [comment]
@JLFN Could you give a short status report?

**Comment by JLFN** [comment]
> @JLFN Could you give a short status report?

It works now. What plugin are you using?
![image](https://user-images.githubusercontent.com/22047436/85220339-f2f24f80-b3aa-11ea-916e-5eb20ab8edd3.png)

**Comment by git-developer** [comment]
What do you mean by _plugin_? For which purpose?

If your problem is finally solved, please don't forget to close this issue.
